name: Test Action 1
on:
  push:
    branches: release/*
jobs:
  parse_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello..."
      - name: Parse Branch Name
        run: echo 'BRANCH_NAME=${GITHUB_REF#refs/heads/release/}' >> $GITHUB_ENV
      - name: Parse Branch Name Last
        run: echo 'BRANCH_NAME_LAST=${GITHUB_REF###*/}' >> $GITHUB_ENV
      #- name: Determine Hosting Channel
      #  env:
      #    CHANNEL_TEST: ${{ steps.get_branch_name.outputs.name == 'prod' && 'live' || steps.get_branch_name.outputs.name }}
      #- name: Echo Channel
      #  env:
      #    CHANNEL: $ {{ steps.get_channel.outputs.channel }}
      #  run: |
      #    echo 'branch_name = $BRANCH_NAME'
      #    echo 'branch_name_last = $BRANCH_NAME_LAST'
      #    echo 'channel_test = $CHANNEL_TEST'
      #    echo 'channel = $CHANNEL'
