name: Test Action 1
on:
  push:
    branches: release/*
jobs:
  use_branch_to_get_channel:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo Hello...
      - name: Found on Internet
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Parse Branch Name
        run: echo BRANCH_NAME=${GITHUB_REF##*/} >> $GITHUB_ENV
      - name: Determine Hosting Channel
        env:
          CHANNEL_TEST: ${{ env.BRANCH_NAME == 'prod' && 'live' || env.BRANCH_NAME }}
        run: echo CHANNEL=${{ env.CHANNEL_TEST }} >> $GITHUB_ENV
      - name: Echo Data
        run: |
          echo branch_name = ${{ env.BRANCH_NAME }}
          echo channel_test = ${{ env.CHANNEL_TEST }}
          echo channel = ${{ env.CHANNEL }}
