name: Test Action 1
on:
  push:
    branches: release/*
jobs:
  parse_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello..."
      #- name: Branch name
      #  run: echo running on branch ${GITHUB_REF##*/}
      - name: Parse Branch Name
        run: echo 'BRANCH_NAME=${GITHUB_REF#refs/heads/}' >> $GITHUB_ENV
      - name: Parse Branch Name Last
        run: echo 'BRANCH_NAME_LAST=${GITHUB_REF##*/}' >> $GITHUB_ENV
      - name: Determine Hosting Channel
        env:
          CHANNEL_TEST: ${{ env.BRANCH_NAME_LAST == 'prod' && 'live' || env.BRANCH_NAME_LAST }}
        run: echo 'CHANNEL=${{ env.CHANNEL_TEST }}' >> $GITHUB_ENV
      - name: Echo Data
        run: |
          echo 'branch_name = ${{ env.BRANCH_NAME }}'
          echo 'branch_name_last = ${{ env.BRANCH_NAME_LAST }}'
          echo 'channel_test = ${{ env.CHANNEL_TEST }}'
          echo 'channel = ${{ env.CHANNEL }}'
